Feat/cell
kohljd/connect_four pull request #2
Opened 2024-01-04 23:15 UTC by mel-langhoff

Basic Cell class created, does not contain any active gameplay logic

2024-01-04 23:58 UTC, kohljd requested changes

2024-01-04 23:58 UTC, kohljd commented on spec/cell_spec.rb
Rspec's "before(:each)" hook requires an "@" before variable names.
- cell -> @cell for line 5, 9, and 13

2024-01-05 02:35 UTC, mel-langhoff commented on spec/cell_spec.rb
Added the "@"

2024-01-05 04:41 UTC, kohljd requested changes

2024-01-05 04:41 UTC, kohljd commented on spec/cell_spec.rb
The variable name must be updated throughout the file in order for it to pass the tests.

```Ruby
RSpec.describe Cell do
    before :each do
        @cell = Cell.new
    end

    it "exists" do
        expect(@cell).to be_an_instance_of Cell
    end

    it "#empty?" do
        expect(@cell.token).to be nil
    end
end
```

2024-01-05 04:41 UTC, kohljd commented on spec/column_spec.rb
> +        expect(column).to be_an_instance_of Column
`expect(column) ` $\rightarrow$ `expect\@column)`

2024-01-05 18:04 UTC, mel-langhoff commented
Changes should be completed in Column spec file

2024-01-05 21:00 UTC, merged